controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_pet_create:
    path: /api/v1/pet/{id}
    controller: App\Controller\PetController::updateOrCreate
    methods: ['POST']
